
IF OBJECT_ID('[eddsdbo].[UserPrice]') IS NULL
BEGIN
	CREATE TABLE [eddsdbo].[UserPrice](
		[UserID] [int] NOT NULL,
		[PricePerHour] [money] NOT NULL,
	 CONSTRAINT [PK_UserPrice] PRIMARY KEY CLUSTERED 
	(
		[UserID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END

